
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 28 14:39:01 COT 2023
//----------------------------------------------------

package ALexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 17;
  public static final int Coma = 36;
  public static final int Op_booleano = 20;
  public static final int If = 6;
  public static final int T_dato = 4;
  public static final int Else = 7;
  public static final int Prompt = 32;
  public static final int Corchete_cerrar = 26;
  public static final int Corchete_abrir = 25;
  public static final int Punto = 35;
  public static final int Console = 30;
  public static final int While = 9;
  public static final int Division = 15;
  public static final int Parentesis_cerrar = 22;
  public static final int Cadena = 5;
  public static final int For = 10;
  public static final int Llave_abrir = 23;
  public static final int EOF = 0;
  public static final int P_coma = 27;
  public static final int Function = 29;
  public static final int error = 1;
  public static final int Linea = 2;
  public static final int Parentesis_abrir = 21;
  public static final int Op_atribucion = 18;
  public static final int ERROR = 38;
  public static final int Do = 8;
  public static final int Op_logico = 16;
  public static final int Case = 34;
  public static final int Identificador = 28;
  public static final int Resta = 13;
  public static final int Llave_cerrar = 24;
  public static final int Multiplicacion = 14;
  public static final int Log = 31;
  public static final int Op_incremento = 19;
  public static final int Numero = 37;
  public static final int Suma = 12;
  public static final int Igual = 11;
  public static final int Swithc = 33;
  public static final int Comillas = 3;
}

